### PR TITLE
Adding support for go modules, refactoring, small bug fixes

### LINKED ISSUE #20: Support Go modules
This works for `dep` style vendor reports, but Go modules' `go.mod`/`go.sum` is not.

We can probably take advantage of `go mod graph` or something like that.

### PR DESCRIPTION
**Pull request by kvincent2**

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -1,438 +1,81 @@
...
-		return GERRIT
-	}
-
-	if strings.Contains(repo, "golang.org/x") {
-		return GERRIT
+		return pkg, nil
 	}
 
-	return ""
+	return nil, nil
```
Comment (cohix) [inline main.go]: So here is usually where we want our "happy path" to end up. When errors happen and we check for them, our error cases usually return inside those conditionals. If everything goes as planned, we should make it to the end of the function and return the happy thing from there. So rather than returning `pkg, nil` inside the conditionals above, you're already assigning `pkg` there, so you can return it here at the end.

File: parse/dep.go [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+)
+
+func ReadGopkg(filepath string) (*models.Pkg, error) {
+	pkgData, err := ioutil.ReadFile(filepath)
+	if err != nil {
+		return nil, errors.New("Failed to read" + filepath + err.Error())
+	}
+
+	var pkg models.Pkg
+	if _, err := toml.Decode(string(pkgData), &pkg); err != nil {
```
Comment (cohix) [inline parse/dep.go]: You can use `toml.Unmarshal` here so you don't need to cast to string

File: parse/mod.go [hunk 3]
```diff
@@ -0,0 +1,59 @@
...
+			if err != nil {
+				return nil, fmt.Errorf("unable to unmarshal module into struct: %w", err)
+			}
+			if module.Version != "" {
+				modArray = append(modArray, module)
+			}
+		}
+	}
+
+	return mapModToPkg(&models.Modules{
```
Comment (cohix) [inline parse/mod.go]: Generally don't want to build a struct inline like this, build it on its own line and pass the variable into the function

File: parse/mod.go [hunk 4]
```diff
@@ -0,0 +1,59 @@
...
+
+		if strings.Contains(mod.Version, "-") {
+			splitVersion := strings.Split(mod.Version, "-")
+			pkg.Revision = splitVersion[len(splitVersion)-1]
+		} else {
+			pkg.Revision = mod.Version
+		}
+		pkgs[i] = pkg
+	}
+	return &models.Pkg{
```
Comment (cohix) [inline parse/mod.go]: Same here, build the struct on its own line and return the variable

File: main.go [hunk 5]
```diff
@@ -1,438 +1,81 @@
...
+		fmt.Println("Parsing dependencies from gopkg.lock")
+		pkg, err = parse.ReadGopkg(wd + depFilePath)
+		if err != nil {
+			return nil, err
 		}
-	case GERRIT:
-		if err := reportObjFromGerrit(&r, m); err != nil {
-			return r, err
+		return pkg, nil
+	case fileExists(wd + goModFilePath):
```
Comment (cohix) [inline main.go]: here and the case above you'll want to use `filepath.Join(wd, gomModFilePath)` to use a "safe" method of creating file path strings.

File: report/report.go [hunk 6]
```diff
@@ -0,0 +1,123 @@
...
+	if err != nil {
+		log.Fatal("Failed to get current commit time", err)
+	}
+	commitTime := strings.TrimSpace(string(commitTimeBytes))
+
+	return commit, commitTime
+}
+
+func (c Config) reportObjFromPkgObj(m models.PkgObject, githubToken string) (models.ReportObject, error) {
+	log.Println("Transforming ", m.Name)
```
Comment (cohix) [inline report/report.go]: This should be removed, since the output is redirected into a file, so this would get included in the report file.

**Review by cohix — CHANGES_REQUESTED** [review]
Overall this is great. I left a few comments but it works as advertised (other than removing the log line I mentioned)

One thing I think we should file an issue for and resolve later is the ability to follow Go vanity URLs. When you see something like `go.1password.io/<blah>`, you can actually make a request to that URL, and the HTML returned has a meta tag that will tell you where the associated Github repo is located. 

Well done!

File: parse/dep_test.go [hunk 7]
```diff
@@ -0,0 +1,56 @@
+package parse
+
+import (
+	"testing"
+)
+
+func TestReadGopkg(t *testing.T) {
+	//filepath := "../Gopkg.lock"
```
Comment (grellyd) [inline parse/dep_test.go:8]: Is this meant to be fully commented out?

File: parse/mod_test.go [hunk 8]
```diff
@@ -0,0 +1,93 @@
...
+
+import (
+	"dep-report/models"
+	"github.com/stretchr/testify/assert"
+	"testing"
+	"time"
+)
+
+func TestParseModules(t *testing.T) {
+	//_, err := ParseModules()
```
Comment (grellyd) [inline parse/mod_test.go]: ditto

File: versioncontrol/versioncontrol.go [hunk 9]
```diff
@@ -0,0 +1,10 @@
+package versioncontrol
+
+import "net/http"
+
+//Client holds the necessary items to make api calls to various version control providers
+//TODO Would be nice to attach repo urls and paths to this object at some point
```
Comment (grellyd) [inline versioncontrol/versioncontrol.go]: If this is remaining as a TODO, I would file it as an issue an remove this comment.

File: versioncontrol/versioncontrol.go [hunk 10]
```diff
@@ -0,0 +1,10 @@
...
+type Client struct {
```
Comment (grellyd) [inline versioncontrol/versioncontrol.go:6]: I would move this struct and its methods in with the generator. I believe that is the only place this is used.

Comment (grellyd) [reply versioncontrol/versioncontrol.go:6]: Then it would be a `report.Client` which makes sense to me. 

Otherwise a `versioncontrol.Client` is also fine. 

Up to you.

File: versioncontrol/github.go [hunk 11]
```diff
@@ -0,0 +1,111 @@
...
+
+	u, err := url.Parse(packageName)
+	if err != nil {
+		return "", fmt.Errorf("unable to parse repo url, %w",err)
+	}
+
+	return strings.Replace(u.Path, "/", "", 1), nil
+}
+
+func (r *Client) getGithub(url string, target interface{}) error {
```
Comment (grellyd) [inline versioncontrol/github.go:84]: I'm of the opinion that object methods should be in the same file as the defined struct, so the file would go:

client.go
```
type Client struct {
...
}

func (c *Client) Foo() error {
...
}

func (c *Client) Bar() error {
...
}

func fooHelper(thing fooable) (fooed){
...
}
```

In my opinion that would greatly increase clarity.

Comment (grellyd) [reply versioncontrol/github.go:84]: If that creates one massive file, then it probably can be broken down further. 

However if that is the case, I would file that as an issue and work on it in the future.

File: versioncontrol/gerrit.go [hunk 12]
```diff
@@ -0,0 +1,137 @@
...
+
+func formatGerritTime(t string) (string, error) {
+	t1, err := time.Parse("2006-01-02 15:04:05.999999999", t)
+	if err != nil {
+		return "", errors.Wrapf(err, "Unable to parse Gerrit time")
+	}
+	return t1.Format("2006-01-02T15:04:05Z"), nil
+}
+
+func (r *Client) getGerrit(url string, target interface{}) error {
```
Comment (grellyd) [inline versioncontrol/gerrit.go:111]: Same to the Client Methods being in the same file as the Client struct, in `client.go`

**Review by grellyd — CHANGES_REQUESTED** [review]

File: parse/dep_test.go (hunk 7 above)
Comment (kvincent2) [reply parse/dep_test.go:8]: The reason that this one is commented out is that it relies on the existence of a gopkg file in the repo, which does not exist since I implemented go modules. I will file an issue to create a test gopkg file that can be used instead.

File: parse/mod_test.go (hunk 8 above)
Comment (kvincent2) [reply parse/mod_test.go]: Fixing this one, missed that.

File: versioncontrol/versioncontrol.go (hunk 10 above)
Comment (kvincent2) [reply versioncontrol/versioncontrol.go:6]: Go does not allow you to define a receiver method outside of the package which defines the receiver. Since we have methods defined on Client in the version control package, we can't simply move it to the report package without further refactoring. 

I set this up with an eye to future additions of urls for each version control provider. Once that improvement is in place, this will make much more sense. I would also want to consider renaming it to something more like "RepoFetcher" to make it's function more clear. Happy to discuss further if you would like.

https://github.com/1Password/dep-report/blob/kb/support-go-modules/versioncontrol/github.go#L84
https://github.com/1Password/dep-report/blob/kb/support-go-modules/versioncontrol/gerrit.go#L113

File: versioncontrol/github.go (hunk 11 above)
Comment (kvincent2) [reply versioncontrol/github.go:84]: Will file issue on this one. Thanks!

File: versioncontrol/gerrit.go (hunk 12 above)
Comment (kvincent2) [reply versioncontrol/gerrit.go:111]: Will file issue.

File: main.go [hunk 13]
```diff
@@ -1,438 +1,80 @@
...
-	case GITHUB:
-		if err := reportObjFromGithub(&r, m, githubToken); err != nil {
-			return r, err
-		}
-	case GITLAB:
-		if err := reportObjFromGitlab(&r, m); err != nil {
-			return r, err
+	switch {
+	case fileExists(filepath.Join(wd, depFilePath)):
+		pkg, err := parse.ReadGopkg(wd + depFilePath)
```
Comment (cohix) [inline main.go:58]: Want to use `filepath.Join` here instead of `+`

**Review by cohix — CHANGES_REQUESTED** [review]
One more thing from me

As for @grellyd 's comments about struct functions being in different files.... I think that's completely fine when a) the file size is too large and/or b) the different files have strong logical groupings of functions (i.e. GitHub and Gerrit makes sense to be in different files IMO)

Otherwise 👍 from me, I'll let Graham finish up the review and y'all can merge it when he's happy.

File: report/report.go (hunk 6 above)
Comment (cohix) [reply report/report.go]: Sounds like we're going to remove this log line and file an issue to post to a Slack webhook instead, so I'm going to resolve this.

File: versioncontrol/versioncontrol.go (hunk 10 above)
Comment (grellyd) [reply versioncontrol/versioncontrol.go:6]: Yep I was thinking the get methods would go in the same package as the client.

Aka make a new receiver package, and move all receiver methods in with it, including the two you linked. Then you get all the functions in the same package, which imo allows for a clearer view to refactoring out repo specific behaviour. 

Again this is just a suggestion.

**Comment by grellyd** [comment]
I think this is looking just fine~ LGTM ✅ 

🚢 🚢 🚢 🌴

**Review by grellyd — APPROVED** [review]

**Review by cohix — APPROVED** [review]
